import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster richColors />

        <div className="grid min-h-dvh grid-rows-[auto_1fr_auto]">
          <header className="border-b px-4 py-2">
            <h1 className="text-2xl font-bold">
              <Link href="/">Next.js Form Validation Examples</Link>
            </h1>
          </header>

          <main className="px-4 py-2">{children}</main>

          <footer>
            <p className="p-4 text-center">
              &copy; {new Date().getFullYear()}{' '}
              <a
                href="https://github.com/coji/form-validate"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:underline"
              >
                GitHub
              </a>
            </p>
          </footer>
        </div>
      </body>
    </html>
  )
}
